dist: bionic

language: php

services:
  - mysql

sudo: false

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.3
    - php: 7.4

before_script:
  - composer self-update
  - echo "memory_limit=3G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "xdebug.mode=coverage" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_install:
  - mysql -e 'CREATE DATABASE jms_jobs;'

install:
  - composer install

script: phpunit --coverage-clover clover
