

language: php

sudo: false

env:
  - XDEBUG_MODE=coverage

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.4

before_script:
  - composer self-update
  - echo "memory_limit=3G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "xdebug.mode=coverage" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer install
  - php tests/Functional/console doctrine:database:create

script: phpunit --coverage-clover clover
