language: php

php:
  - 7.2
  - 7.4
  - hhvm

env:
  - SYMFONY_VERSION="5.4.*" DB=sqlite

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.4
    - php: hhvm
  allow_failures:
    - php: hhvm

notifications:
  on_success: never

  on_failure: never

before_script:
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit
