#!/usr/bin/env php
<?php

require_once __DIR__.'/AppKernel.php';

use JMS\JobQueueBundle\Console\Application;
use JMS\JobQueueBundle\Tests\Functional\AppKernel;

$kernel = new AppKernel('test', true);
$kernel->boot();

$app = new Application($kernel);
$app->run();